# Generated by Django 5.2 on 2025-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('last_serviced_date', models.DateField()),
            ],
        ),
    ]
