# Generated by Django 5.2 on 2025-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='reg_no',
            field=models.CharField(default='NA1234', max_length=20),
        ),
    ]
