# Generated by Django 5.2 on 2025-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_servicerecord_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='progress',
            field=models.CharField(choices=[('Under Maintenance', 'Under Maintenance'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
