# Generated by Django 5.2 on 2025-05-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_servicerecord_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='last_serviced_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='progress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
