# Generated by Django 5.2 on 2025-05-08 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_alter_servicerecord_last_serviced_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('progress', models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting for Parts', 'Waiting for Parts'), ('Completed', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicerecord')),
            ],
        ),
    ]
